import "server-only";

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

type DateInput = Date | string;
type MoneyInput = number | string;

export type PayStubPdfInput = {
  documentId: string;
  companyId: string;
  companyName: string;
  employeeId: string;
  employeeDisplayName: string;
  payrollRunId: string;
  payPeriodStart: DateInput;
  payPeriodEnd: DateInput;
  payDate: DateInput;
  rateType: string;
  rateAmount: MoneyInput;
  totalHours: MoneyInput;
  grossPay: MoneyInput;
  deductions: MoneyInput;
  netPay: MoneyInput;
  generatedDate: DateInput;
};

type FontSet = {
  regular: PDFFont;
  bold: PDFFont;
};

const STORAGE_BUCKET_COMPANIES_PREFIX = "companies";
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 56;
const INK = rgb(0.12, 0.12, 0.12);
const MUTED = rgb(0.42, 0.42, 0.42);
const RULE = rgb(0.78, 0.78, 0.78);
const SOFT_RULE = rgb(0.9, 0.9, 0.9);

export async function generatePayStubPdf(input: PayStubPdfInput): Promise<Buffer | Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
  };

  drawPayStub(page, fonts, input);

  const bytes = await pdf.save();
  return Buffer.from(bytes);
}

export function buildPayStubFileName(input: Pick<PayStubPdfInput, "employeeDisplayName" | "payDate" | "documentId">): string {
  const employeeSlug = slugify(input.employeeDisplayName) || "employee";
  const payDateSlug = formatDateForFileName(input.payDate);
  const documentSlug = slugify(input.documentId) || "document";

  return `pay-stub-${employeeSlug}-${payDateSlug}-${documentSlug}.pdf`;
}

export function buildPayStubStoragePath(
  input: Pick<PayStubPdfInput, "companyId" | "payrollRunId" | "documentId">
): string {
  return [
    STORAGE_BUCKET_COMPANIES_PREFIX,
    encodePathSegment(input.companyId),
    "payroll-runs",
    encodePathSegment(input.payrollRunId),
    "pay-stubs",
    `${encodePathSegment(input.documentId)}.pdf`,
  ].join("/");
}

function drawPayStub(page: PDFPage, fonts: FontSet, input: PayStubPdfInput) {
  let y = PAGE_HEIGHT - MARGIN;

  drawText(page, "Credo", MARGIN, y, 18, fonts.bold);
  drawText(page, "Generated payroll document", PAGE_WIDTH - MARGIN - 166, y + 2, 9, fonts.regular, MUTED);

  y -= 44;
  drawText(page, "Pay Stub", MARGIN, y, 28, fonts.bold);
  y -= 22;
  drawText(page, input.companyName, MARGIN, y, 12, fonts.regular, MUTED);

  y -= 34;
  drawRule(page, y);
  y -= 28;

  const payPeriod = `${formatDisplayDate(input.payPeriodStart)} to ${formatDisplayDate(input.payPeriodEnd)}`;
  drawKeyValueGrid(page, fonts, y, [
    ["Employee", input.employeeDisplayName],
    ["Company", input.companyName],
    ["Pay period", payPeriod],
    ["Pay date", formatDisplayDate(input.payDate)],
    ["Payroll run", input.payrollRunId],
    ["Document", input.documentId],
  ]);

  y -= 118;
  drawSectionHeading(page, fonts, "Earnings summary", y);
  y -= 26;
  drawSummaryTable(page, fonts, y, [
    ["Rate type", formatLabel(input.rateType)],
    ["Rate amount", formatCurrency(input.rateAmount)],
    ["Total hours", formatNumber(input.totalHours)],
    ["Gross pay", formatCurrency(input.grossPay)],
  ]);

  y -= 128;
  drawSectionHeading(page, fonts, "Deductions summary", y);
  y -= 26;
  drawSummaryTable(page, fonts, y, [["Deductions", formatCurrency(input.deductions)]]);

  y -= 76;
  drawNetPay(page, fonts, y, formatCurrency(input.netPay));

  y = 98;
  drawRule(page, y);
  y -= 22;
  drawText(page, `Generated ${formatDisplayDate(input.generatedDate)}`, MARGIN, y, 9, fonts.regular, MUTED);
  drawText(
    page,
    "Generated by Credo. Review payroll values before issuing.",
    MARGIN,
    y - 16,
    9,
    fonts.regular,
    MUTED
  );
}

function drawKeyValueGrid(page: PDFPage, fonts: FontSet, startY: number, rows: Array<[string, string]>) {
  const leftX = MARGIN;
  const rightX = 326;
  const rowGap = 34;

  rows.forEach(([label, value], index) => {
    const columnX = index % 2 === 0 ? leftX : rightX;
    const rowY = startY - Math.floor(index / 2) * rowGap;

    drawText(page, label.toUpperCase(), columnX, rowY, 8, fonts.bold, MUTED);
    drawText(page, value || "Not provided", columnX, rowY - 14, 11, fonts.regular, INK, 214);
  });
}

function drawSummaryTable(page: PDFPage, fonts: FontSet, startY: number, rows: Array<[string, string]>) {
  const labelX = MARGIN;
  const valueX = PAGE_WIDTH - MARGIN - 156;
  const rowHeight = 28;

  rows.forEach(([label, value], index) => {
    const rowY = startY - index * rowHeight;
    drawText(page, label, labelX, rowY, 11, fonts.regular, INK);
    drawText(page, value, valueX, rowY, 11, fonts.bold, INK);
    drawLine(page, MARGIN, rowY - 10, PAGE_WIDTH - MARGIN, rowY - 10, SOFT_RULE);
  });
}

function drawNetPay(page: PDFPage, fonts: FontSet, y: number, value: string) {
  page.drawRectangle({
    x: MARGIN,
    y: y - 28,
    width: PAGE_WIDTH - MARGIN * 2,
    height: 54,
    borderColor: RULE,
    borderWidth: 1,
    color: rgb(0.97, 0.97, 0.97),
  });

  drawText(page, "Net pay", MARGIN + 18, y + 2, 12, fonts.bold, INK);
  drawText(page, value, PAGE_WIDTH - MARGIN - 174, y + 2, 18, fonts.bold, INK);
}

function drawSectionHeading(page: PDFPage, fonts: FontSet, text: string, y: number) {
  drawText(page, text, MARGIN, y, 14, fonts.bold, INK);
  drawLine(page, MARGIN, y - 8, PAGE_WIDTH - MARGIN, y - 8, RULE);
}

function drawRule(page: PDFPage, y: number) {
  drawLine(page, MARGIN, y, PAGE_WIDTH - MARGIN, y, RULE);
}

function drawLine(page: PDFPage, startX: number, startY: number, endX: number, endY: number, color = RULE) {
  page.drawLine({
    start: { x: startX, y: startY },
    end: { x: endX, y: endY },
    thickness: 1,
    color,
  });
}

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  size: number,
  font: PDFFont,
  color = INK,
  maxWidth?: number
) {
  const safeText = normalizeText(text);

  if (!maxWidth || font.widthOfTextAtSize(safeText, size) <= maxWidth) {
    page.drawText(safeText, { x, y, size, font, color });
    return;
  }

  page.drawText(truncateToWidth(safeText, font, size, maxWidth), { x, y, size, font, color });
}

function formatCurrency(value: MoneyInput) {
  const amount = toNumber(value);

  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

function formatNumber(value: MoneyInput) {
  const amount = toNumber(value);

  return new Intl.NumberFormat("en-CA", {
    minimumFractionDigits: Number.isInteger(amount) ? 0 : 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

function formatDisplayDate(value: DateInput) {
  const date = toDate(value);

  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    timeZone: "UTC",
  }).format(date);
}

function formatDateForFileName(value: DateInput) {
  const date = toDate(value);
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const day = String(date.getUTCDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function formatLabel(value: string) {
  return normalizeText(value)
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function slugify(value: string) {
  return normalizeText(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function encodePathSegment(value: string) {
  const normalized = normalizeText(value).trim();

  if (!normalized) {
    throw new Error("Pay stub storage path requires non-empty identifiers.");
  }

  if (normalized.includes("/")) {
    throw new Error("Pay stub storage path identifiers cannot contain slashes.");
  }

  return normalized;
}

function toNumber(value: MoneyInput) {
  const amount = typeof value === "number" ? value : Number(value);

  if (!Number.isFinite(amount)) {
    throw new Error("Pay stub PDF received a non-numeric payroll value.");
  }

  return amount;
}

function toDate(value: DateInput) {
  const date = value instanceof Date ? value : new Date(value);

  if (Number.isNaN(date.getTime())) {
    throw new Error("Pay stub PDF received an invalid date value.");
  }

  return date;
}

function normalizeText(value: string) {
  return value.replace(/[\u0000-\u001f\u007f]+/g, " ").trim();
}

function truncateToWidth(value: string, font: PDFFont, size: number, maxWidth: number) {
  const ellipsis = "...";
  let next = value;

  while (next.length > 0 && font.widthOfTextAtSize(`${next}${ellipsis}`, size) > maxWidth) {
    next = next.slice(0, -1);
  }

  return `${next.trimEnd()}${ellipsis}`;
}
