export const en = {
  common: {
    back: "Back",
    cancel: "Cancel",
    create: "Create",
    delete: "Delete",
    continue: "Continue",
    next: "Next",
    saveChanges: "Save changes",
    tryAgain: "Try again",
    current: "Current",
    noDataFallback: "Not provided",
    notifications: "Notifications",
  },
  topbar: {
    workspaceName: "Credo workspace",
    companiesLabel: "Companies",
    noCompanies: "No companies yet.",
    addCompany: "Add company",
    manageCompanies: "Manage companies",
    searchWorkspacePlaceholder: "Search workspace",
    today: "Today",
  },
  navigation: {
    overview: "Overview",
    team: "Team",
    payroll: "Payroll",
    documents: "Documents",
    insights: "Insights",
    compliance: "Compliance",
  },
  company: {
    create: {
      title: "Company address",
      subtitle: "Search for the company address.",
      addressLabel: "Address",
      addressPlaceholder: "Search for a company address",
      addressRequired: "Address is required.",
      createButton: "Create company",
      addButton: "Add company",
      creating: "Creating…",
      enteringDetailsTitle: "Enter company details",
      enteringDetailsSubtitle:
        "Add another company workspace for payroll, invoicing, and operations.",
      firstCompanyTitle: "Create your first company",
      firstCompanySubtitle: "Start with your company name. You can add more details later.",
      companyNameLabel: "Company name",
      companyNameHint: "Shown in Credo.",
      companyNameRequired: "Company name is required.",
      requiredAddressHint: "Select an address or enter it manually.",
    },
    profile: {
      creating: "Creating…",
      saving: "Saving…",
      createButton: "Create company",
      saveButton: "Save changes",
    },
    delete: {
      title: "Confirm deletion",
      subtitle:
        "Deleting this company will remove payroll, invoice, document, and activity data from active views.",
      confirmCheckbox:
        "I understand this company will no longer appear in dashboard activity.",
      deleteButton: "Delete company",
      deleting: "Deleting…",
      backButton: "Back",
      successToast: "Company deleted",
      reasonStepTitle: "Delete company",
      reasonStepSubtitle:
        "This removes the company from your dashboard. We'll keep an audit record.",
      reasonLabel: "Reason",
      reasonSelectPlaceholder: "Select a reason",
      reasonOtherLabel: "Tell us why",
      reasonOtherPlaceholder: "Optional details",
      reasonContinueError: "Select a reason to continue.",
      continueButton: "Continue",
      summaryEmployees: "employees",
      payrollNumberLabel: "Payroll number",
      hstNumberLabel: "HST number",
      binNumberLabel: "BIN number",
      softNoticeContinueTitle: "We couldn't continue",
      softNoticeDeleteTitle: "We couldn't delete this company",
      acknowledgeError: "Confirm that you understand this will remove company data from the dashboard.",
      reasonRequiredError: "Select a reason before deleting this company.",
      genericDeleteError: "We couldn’t delete the company. Try again.",
      reasons: {
        createdByMistake: "Created by mistake",
        noLongerActive: "Company is no longer active",
        duplicate: "Duplicate company",
        movedSystem: "Moved to another system",
        testingData: "Testing/demo data",
        other: "Other",
      },
      pageState: {
        notFoundTitle: "Company not found",
        notFoundDetail: "This company may have been removed or is not available in your workspace.",
        loadErrorTitle: "We couldn't load delete details",
        loadErrorDetail: "Try again. If this keeps happening, check your connection and data access settings.",
      },
    },
    dangerZone: {
      label: "Danger zone",
      title: "Delete company",
      description: "Delete this company when it's no longer needed.",
      cta: "Delete company",
    },
    setup: {
      stepLabel: "Step {step} of {totalSteps}",
      completeSetupTitle: "Complete setup",
      completeSetupEyebrow: "Next",
      completeSetupDescription: "Add tax details when ready.",
      completeSetupButton: "Complete setup",
      directDepositTitle: "Direct deposit info",
      directDepositEyebrow: "Identifiers",
      quickActionsTitle: "Quick actions",
      quickActionsEyebrow: "Company",
      actionsTitle: "Company actions",
      actionsEyebrow: "Menu",
      fundingDueTitle: "Funding due tomorrow",
      fundingDueEyebrow: "Operational focus",
      fundingDueDescription: "Confirm by 4:00 PM.",
    },
  },
  addressField: {
    searchUnavailableError: "Address search is unavailable right now.",
    searchUnavailableTitle: "Address search is unavailable",
    searchUnavailableDetail: "Enter the address manually to continue.",
    manualEntryCta: "I don't see my address",
    addUnitSuite: "Add unit/suite",
    changeAddress: "Change address",
    unitSuiteOptional: "Unit, suite, etc. (optional)",
    manualUnitSuiteOptional: "Unit/suite (optional)",
    city: "City",
    provinceState: "Province/state",
    postalCode: "Postal code",
    country: "Country",
  },
  runPayroll: {
    eyebrow: "Payroll",
    title: "Run payroll",
    subtitle:
      "Prepare the pay period, choose employees, review totals, and submit the run from one focused workflow.",
    actions: {
      runPayroll: "Run payroll",
      reviewDraft: "Review draft",
      export: "Export",
      continue: "Continue",
      close: "Close payroll workflow",
      submitPayroll: "Submit payroll",
    },
    filters: [
      { id: "all", label: "All" },
      { id: "hourly", label: "Hourly" },
      { id: "salary", label: "Salary" },
      { id: "review", label: "Needs review" },
    ],
    timeline: {
      title: "April payroll run",
      subtitle: "A quiet view of what is ready, what needs review, and what will be submitted.",
      items: [
        {
          id: "period",
          title: "Pay period prepared",
          description: "Regular payroll for Apr 1-15 is ready for employee selection.",
          status: "Ready",
          tone: "complete",
          meta: ["Semi-monthly", "Apr 19 pay date"],
        },
        {
          id: "employees",
          title: "Employees included",
          description: "Eight employees are included. Two hourly entries need a final look.",
          status: "Review",
          tone: "pending",
          meta: ["8 employees", "2 time entries"],
        },
        {
          id: "totals",
          title: "Totals calculated",
          description: "Gross pay, deductions, and net pay are estimated for review.",
          status: "Draft",
          tone: "pending",
          meta: ["$42,800 gross", "$31,920 net"],
        },
        {
          id: "submit",
          title: "Submit payroll",
          description: "Submit after confirming funding and payroll details.",
          status: "Next",
          tone: "pending",
          meta: ["Audit record", "Funding reminder"],
        },
      ],
    },
    summary: {
      eyebrow: "Run summary",
      title: "Payroll snapshot",
      statusValue: "Draft",
      employeeTotals: "Employee totals",
      sections: [
        {
          id: "period",
          title: "Payroll period",
          items: [
            { label: "Pay period", value: "Apr 1-15, 2026" },
            { label: "Pay date", value: "Apr 19, 2026" },
            { label: "Payroll type", value: "Regular" },
          ],
        },
        {
          id: "totals",
          title: "Totals",
          items: [
            { label: "Employees included", value: "8" },
            { label: "Gross pay", value: "$42,800.00" },
            { label: "Deductions", value: "$10,880.00" },
            { label: "Net pay", value: "$31,920.00" },
          ],
        },
        {
          id: "status",
          title: "Status",
          items: [
            { label: "Run status", value: "Ready to review" },
            { label: "Funding", value: "Confirm by 4:00 PM" },
          ],
        },
      ],
    },
    steps: {
      progress: "Step {step} of {total}",
      items: [
        {
          title: "Payroll setup",
          subtitle: "Start with the pay period, pay date, and run type.",
        },
        {
          title: "Select employees",
          subtitle: "Choose who should be included in this payroll run.",
        },
        {
          title: "Review payroll",
          subtitle: "Check employee totals, deductions, and quiet warnings before submitting.",
        },
        {
          title: "Confirm and submit",
          subtitle: "Confirm the run details and create an audit record.",
        },
      ],
    },
    fields: {
      payPeriod: {
        label: "Pay period",
        options: ["Apr 1-15, 2026", "Apr 16-30, 2026", "May 1-15, 2026"],
      },
      payDate: {
        label: "Pay date",
        defaultValue: "2026-04-19",
      },
      payrollType: {
        label: "Payroll type",
        options: ["Regular", "Bonus", "Off-cycle"],
      },
      employees: {
        allEmployees: "All employees",
      },
    },
    employeeFilters: ["All departments", "Operations", "Salary", "Hourly"],
    employees: [
      {
        id: "maya",
        name: "Maya Chen",
        detail: "Operations · Salary · Ready",
        amount: "$6,250.00",
        defaultSelected: true,
      },
      {
        id: "jonas",
        name: "Jonas Patel",
        detail: "Operations · Hourly · Time entry review",
        amount: "$3,840.00",
        defaultSelected: true,
      },
      {
        id: "amelia",
        name: "Amelia Brooks",
        detail: "Client success · Salary · Ready",
        amount: "$5,920.00",
        defaultSelected: true,
      },
      {
        id: "noah",
        name: "Noah Singh",
        detail: "Field team · Hourly · Time entry review",
        amount: "$2,760.00",
        defaultSelected: true,
      },
    ],
    reviewTotals: [
      { label: "Gross pay", value: "$42,800.00" },
      { label: "Deductions", value: "$10,880.00" },
      { label: "Net pay", value: "$31,920.00" },
    ],
    validation: {
      title: "We couldn't continue",
      selectEmployee: "Select at least one employee before reviewing payroll.",
      confirmationRequired: "Confirm that the payroll details are ready to submit.",
      noticeTitle: "Review note",
      noticeDescription: "Two hourly entries are flagged for review before final submission.",
    },
    confirmation: {
      title: "Submission audit",
      checkbox: "I have reviewed the payroll details and confirm this run is ready to submit.",
      auditNote:
        "Submitting payroll records the selected employees, totals, pay date, and user action in the audit trail.",
    },
    microcopy: {
      payPeriod: "Choose the earning period covered by this run.",
      payDate: "Employees will see this as the scheduled payment date.",
      payrollType: "Use off-cycle only when this run sits outside the regular schedule.",
      allEmployees: "Includes every active employee currently eligible for payroll.",
    },
  },
  documents: {
    eyebrow: "Documents",
    title: "Documents",
    description: "Browse generated payroll records, employee letters, tax forms, and company files from one quiet workspace.",
    tabs: [
      { id: "pay-stubs", label: "Pay stubs" },
      { id: "letters", label: "Letters" },
      { id: "tax-forms", label: "Tax forms" },
      { id: "company-documents", label: "Company documents" },
    ],
    actions: {
      eyebrow: "Actions",
      title: "Document actions",
      requestDocuments: "Request documents",
      uploadDocuments: "Upload documents",
    },
    rowActions: {
      open: "Open",
      download: "Download",
    },
    sourceLabels: {
      generated: "Generated",
      uploaded: "Uploaded",
    },
    documentCount: {
      single: "document",
      plural: "documents",
    },
    emptyState: {
      title: "No documents yet",
      description: "Pay stubs, letters, and tax forms will appear here once generated.",
      hint: "Try another document tab or check back after the next payroll run.",
    },
    filters: {
      eyebrow: "Filters",
      title: "Refine documents",
      tabsLabel: "Type",
      sourceLabel: "Source",
      monthLabel: "Period",
      sources: [
        { id: "all", label: "All sources" },
        { id: "generated", label: "Generated" },
        { id: "uploaded", label: "Uploaded" },
      ],
      months: [
        { id: "all", label: "All periods" },
        { id: "2026-04", label: "April 2026" },
        { id: "2026-03", label: "March 2026" },
        { id: "2025-12", label: "December 2025" },
      ],
    },
    groups: [
      { id: "april-2026", label: "April 2026" },
      { id: "march-2026", label: "March 2026" },
      { id: "december-2025", label: "December 2025" },
    ],
    items: {
      mayaPaystubApril: {
        title: "Maya Chen pay stub",
        subtitle: "Semi-monthly payroll record for the April 19, 2026 pay date.",
        meta: "Pay stub · Apr 19, 2026",
      },
      jonasPaystubApril: {
        title: "Jonas Patel pay stub",
        subtitle: "Hourly payroll record with reviewed time entries for the April 19, 2026 run.",
        meta: "Pay stub · Apr 19, 2026",
      },
      ameliaBonusLetter: {
        title: "Amelia Brooks bonus letter",
        subtitle: "Employee letter prepared for the spring performance payment.",
        meta: "Letter · Apr 12, 2026",
      },
      mayaVerificationLetter: {
        title: "Maya Chen employment verification",
        subtitle: "Uploaded employment letter shared with an external lender.",
        meta: "Letter · Mar 22, 2026",
      },
      mayaT4: {
        title: "Maya Chen T4",
        subtitle: "Year-end tax form for the 2025 filing season.",
        meta: "Tax form · Dec 31, 2025",
      },
      jonasT4: {
        title: "Jonas Patel T4",
        subtitle: "Year-end tax form prepared for payroll remittance records.",
        meta: "Tax form · Dec 31, 2025",
      },
      noahRoe: {
        title: "Noah Singh record of employment",
        subtitle: "Employment record prepared after the final March payroll cycle.",
        meta: "ROE · Mar 28, 2026",
      },
      boardResolution: {
        title: "Board resolution package",
        subtitle: "Uploaded company approval package for payroll and banking records.",
        meta: "Company document · Apr 8, 2026",
      },
    },
  },
  actions: {
    createCompany: {
      cannotCreateTitle: "We couldn’t create the company",
      legalNameMissing: "Add the legal name and try again.",
      genericDescription: "Check the required details and try again.",
    },
    profile: {
      companyNameRequired: "Company name is required. Add it and try again.",
      legalNameRequired: "Legal name is required. Add it and try again.",
      saveError: "We couldn’t save company details. Check required fields and try again.",
      updateError: "We couldn’t update company details. Check required fields and try again.",
      confirmError: "We couldn’t confirm the company yet. Review details and try again.",
    },
  },
} as const;

export type ContentDictionary = typeof en;
