export const en = {
  common: {
    back: "Back",
    cancel: "Cancel",
    create: "Create",
    delete: "Delete",
    continue: "Continue",
    next: "Next",
    saveChanges: "Save changes",
    tryAgain: "Try again",
    current: "Current",
    noDataFallback: "Not provided",
    notifications: "Notifications",
  },
  topbar: {
    workspaceName: "Credo workspace",
    companiesLabel: "Companies",
    noCompanies: "No companies yet.",
    addCompany: "Add company",
    manageCompanies: "Manage companies",
    searchWorkspacePlaceholder: "Search workspace",
    today: "Today",
  },
  navigation: {
    overview: "Overview",
    team: "Team",
    employees: "Employees",
    payroll: "Payroll",
    documents: "Documents",
    insights: "Insights",
    compliance: "Compliance",
  },
  company: {
    create: {
      title: "Company address",
      subtitle: "Search for the company address.",
      addressLabel: "Address",
      addressPlaceholder: "Search for a company address",
      addressRequired: "Address is required.",
      createButton: "Create company",
      addButton: "Add company",
      creating: "Creating…",
      enteringDetailsTitle: "Enter company details",
      enteringDetailsSubtitle:
        "Add another company workspace for payroll, invoicing, and operations.",
      firstCompanyTitle: "Create your first company",
      firstCompanySubtitle: "Start with your company name. You can add more details later.",
      companyNameLabel: "Company name",
      companyNameHint: "Shown in Credo.",
      companyNameRequired: "Company name is required.",
      requiredAddressHint: "Select an address or enter it manually.",
    },
    profile: {
      creating: "Creating…",
      saving: "Saving…",
      createButton: "Create company",
      saveButton: "Save changes",
    },
    delete: {
      title: "Confirm deletion",
      subtitle:
        "Deleting this company will remove payroll, invoice, document, and activity data from active views.",
      confirmCheckbox:
        "I understand this company will no longer appear in dashboard activity.",
      deleteButton: "Delete company",
      deleting: "Deleting…",
      backButton: "Back",
      successToast: "Company deleted",
      reasonStepTitle: "Delete company",
      reasonStepSubtitle:
        "This removes the company from your dashboard. We'll keep an audit record.",
      reasonLabel: "Reason",
      reasonSelectPlaceholder: "Select a reason",
      reasonOtherLabel: "Tell us why",
      reasonOtherPlaceholder: "Optional details",
      reasonContinueError: "Select a reason to continue.",
      continueButton: "Continue",
      summaryEmployees: "employees",
      payrollNumberLabel: "Payroll number",
      hstNumberLabel: "HST number",
      binNumberLabel: "BIN number",
      softNoticeContinueTitle: "We couldn't continue",
      softNoticeDeleteTitle: "We couldn't delete this company",
      acknowledgeError: "Confirm that you understand this will remove company data from the dashboard.",
      reasonRequiredError: "Select a reason before deleting this company.",
      genericDeleteError: "We couldn’t delete the company. Try again.",
      reasons: {
        createdByMistake: "Created by mistake",
        noLongerActive: "Company is no longer active",
        duplicate: "Duplicate company",
        movedSystem: "Moved to another system",
        testingData: "Testing/demo data",
        other: "Other",
      },
      pageState: {
        notFoundTitle: "Company not found",
        notFoundDetail: "This company may have been removed or is not available in your workspace.",
        loadErrorTitle: "We couldn't load delete details",
        loadErrorDetail: "Try again. If this keeps happening, check your connection and data access settings.",
      },
    },
    dangerZone: {
      label: "Danger zone",
      title: "Delete company",
      description: "Delete this company when it's no longer needed.",
      cta: "Delete company",
    },
    setup: {
      stepLabel: "Step {step} of {totalSteps}",
      completeSetupTitle: "Complete setup",
      completeSetupEyebrow: "Next",
      completeSetupDescription: "Add tax details when ready.",
      completeSetupButton: "Complete setup",
      directDepositTitle: "Direct deposit info",
      directDepositEyebrow: "Identifiers",
      quickActionsTitle: "Quick actions",
      quickActionsEyebrow: "Company",
      actionsTitle: "Company actions",
      actionsEyebrow: "Menu",
      fundingDueTitle: "Funding due tomorrow",
      fundingDueEyebrow: "Operational focus",
      fundingDueDescription: "Confirm by 4:00 PM.",
    },
  },
  addressField: {
    searchUnavailableError: "Address search is unavailable right now.",
    searchUnavailableTitle: "Address search is unavailable",
    searchUnavailableDetail: "Enter the address manually to continue.",
    manualEntryCta: "I don't see my address",
    addUnitSuite: "Add unit/suite",
    changeAddress: "Change address",
    unitSuiteOptional: "Unit, suite, etc. (optional)",
    manualUnitSuiteOptional: "Unit/suite (optional)",
    city: "City",
    provinceState: "Province/state",
    postalCode: "Postal code",
    country: "Country",
  },
  runPayroll: {
    eyebrow: "Payroll",
    title: "Run payroll",
    subtitle: "Prepare the pay period, choose employees, review totals, and submit the run from one focused workflow.",
    page: {
      eyebrow: "Payroll",
      title: "Payroll",
      description: "Scan payroll runs by month, filter quickly, and keep action centered on the runs that need attention.",
      runCount: {
        single: "run",
        plural: "runs",
      },
      columns: {
        employees: "Employees",
        total: "Total amount",
      },
      actions: {
        view: "View",
        continue: "Continue",
        download: "Download",
      },
      empty: {
        title: "No payroll runs match these filters",
        description: "Try a wider date range or clear one of the filters in the right rail.",
      },
    },
    actions: {
      runPayroll: "Run payroll",
      continue: "Continue",
      close: "Close payroll workflow",
      submitPayroll: "Submit payroll",
    },
    filtersPanel: {
      eyebrow: "Filters",
      title: "Refine payroll",
      quickLabel: "Quick filters",
      statusLabel: "Status",
      companyLabel: "Company",
      teamLabel: "Team",
      employeeLabel: "Employee",
      payrollTypeLabel: "Payroll type",
      dateRangeLabel: "Date range",
      quickFilters: [
        { id: "all", label: "All runs" },
        { id: "action-required", label: "Action required" },
        { id: "completed", label: "Completed" },
        { id: "off-cycle", label: "Off-cycle" },
      ],
      statuses: [
        { id: "all", label: "All statuses" },
        { id: "draft", label: "Draft" },
        { id: "completed", label: "Completed" },
      ],
      companies: [
        { id: "all", label: "All companies" },
        { id: "northline", label: "Northline" },
        { id: "willow", label: "Willow" },
        { id: "harbor", label: "Harbor" },
      ],
      teams: [
        { id: "all", label: "All teams" },
        { id: "operations", label: "Operations" },
        { id: "client-success", label: "Client success" },
        { id: "finance", label: "Finance" },
        { id: "leadership", label: "Leadership" },
      ],
      employees: [
        { id: "all", label: "All employees" },
        { id: "maya-chen", label: "Maya Chen" },
        { id: "jonas-patel", label: "Jonas Patel" },
        { id: "amelia-brooks", label: "Amelia Brooks" },
        { id: "noah-singh", label: "Noah Singh" },
      ],
      payrollTypes: [
        { id: "all", label: "All payroll types" },
        { id: "regular", label: "Regular" },
        { id: "bonus", label: "Bonus" },
        { id: "off-cycle", label: "Off-cycle" },
      ],
      dateRanges: [
        { id: "all", label: "All time" },
        { id: "april-2026", label: "April 2026" },
        { id: "q1-2026", label: "Q1 2026" },
        { id: "fy-2026", label: "2026" },
        { id: "fy-2025", label: "2025" },
      ],
    },
    runs: {
      statuses: {
        draft: "Draft",
        completed: "Completed",
      },
      types: {
        regular: "Regular",
        bonus: "Bonus",
        offCycle: "Off-cycle",
      },
      entities: {
        companies: {
          northline: "Northline",
          willow: "Willow",
          harbor: "Harbor",
        },
        teams: {
          operations: "Operations",
          clientSuccess: "Client success",
          finance: "Finance",
          leadership: "Leadership",
        },
      },
      items: {
        northlineApril: {
          payPeriod: "Apr 16-30, 2026",
          employeeSummary: "Maya Chen, Jonas Patel, +6 more",
        },
        willowApril: {
          payPeriod: "Apr 16-30, 2026",
          employeeSummary: "Amelia Brooks, +4 more",
        },
        harborBonus: {
          payPeriod: "Apr 1-12, 2026",
          employeeSummary: "Maya Chen, Amelia Brooks",
        },
        northlineMarchOffCycle: {
          payPeriod: "Mar 22-28, 2026",
          employeeSummary: "Jonas Patel",
        },
        harborYearEnd: {
          payPeriod: "Dec 16-31, 2025",
          employeeSummary: "Noah Singh, +5 more",
        },
      },
    },
    filters: [
      { id: "all", label: "All" },
      { id: "hourly", label: "Hourly" },
      { id: "salary", label: "Salary" },
      { id: "review", label: "Needs review" },
    ],
    timeline: {
      title: "April payroll run",
      subtitle: "A quiet view of what is ready, what needs review, and what will be submitted.",
      items: [
        {
          id: "period",
          title: "Pay period prepared",
          description: "Regular payroll for Apr 1-15 is ready for employee selection.",
          status: "Ready",
          tone: "complete",
          meta: ["Semi-monthly", "Apr 19 pay date"],
        },
        {
          id: "employees",
          title: "Employees included",
          description: "Eight employees are included. Two hourly entries need a final look.",
          status: "Review",
          tone: "pending",
          meta: ["8 employees", "2 time entries"],
        },
        {
          id: "totals",
          title: "Totals calculated",
          description: "Gross pay, deductions, and net pay are estimated for review.",
          status: "Draft",
          tone: "pending",
          meta: ["$42,800 gross", "$31,920 net"],
        },
        {
          id: "submit",
          title: "Submit payroll",
          description: "Submit after confirming funding and payroll details.",
          status: "Next",
          tone: "pending",
          meta: ["Audit record", "Funding reminder"],
        },
      ],
    },
    summary: {
      eyebrow: "Run summary",
      title: "Payroll snapshot",
      statusValue: "Draft",
      employeeTotals: "Employee totals",
      sections: [
        {
          id: "period",
          title: "Payroll period",
          items: [
            { label: "Pay period", value: "Apr 1-15, 2026" },
            { label: "Pay date", value: "Apr 19, 2026" },
            { label: "Payroll type", value: "Regular" },
          ],
        },
        {
          id: "totals",
          title: "Totals",
          items: [
            { label: "Employees included", value: "8" },
            { label: "Gross pay", value: "$42,800.00" },
            { label: "Deductions", value: "$10,880.00" },
            { label: "Net pay", value: "$31,920.00" },
          ],
        },
        {
          id: "status",
          title: "Status",
          items: [
            { label: "Run status", value: "Ready to review" },
            { label: "Funding", value: "Confirm by 4:00 PM" },
          ],
        },
      ],
    },
    steps: {
      progress: "Step {step} of {total}",
      items: [
        {
          title: "Payroll setup",
          subtitle: "Start with the pay period, pay date, and run type.",
        },
        {
          title: "Employee pay setup",
          subtitle: "Choose employees, confirm their compensation type, and adjust calculated hours when needed.",
        },
        {
          title: "Review payroll",
          subtitle: "Check pay period dates, gross pay estimates, and any manual hour overrides before submitting.",
        },
        {
          title: "Confirm and submit",
          subtitle: "Confirm the run details and create an audit record.",
        },
      ],
    },
    fields: {
      payPeriod: {
        label: "Pay period",
        options: [
          { id: "apr-1-15", label: "Apr 1-15, 2026", startDate: "2026-04-01", endDate: "2026-04-15" },
          { id: "apr-16-30", label: "Apr 16-30, 2026", startDate: "2026-04-16", endDate: "2026-04-30" },
          { id: "may-1-15", label: "May 1-15, 2026", startDate: "2026-05-01", endDate: "2026-05-15" },
        ],
      },
      payDate: {
        label: "Pay date",
        defaultValue: "2026-04-19",
      },
      payrollType: {
        label: "Payroll type",
        options: ["Regular", "Bonus", "Off-cycle"],
      },
      employees: {
        allEmployees: "All employees",
      },
      useCustomDates: "Use custom dates",
      customDateHelper: "Use this only when the pay period does not match the regular payroll schedule.",
      startDate: "Start date",
      endDate: "End date",
      invalidDateRange: "End date must be after the start date.",
      payDateBeforeEndDate: "Pay date must be on or after the end date.",
      rateType: "Rate type",
      rateAmount: "Rate amount",
      hourly: "Hourly",
      daily: "Daily",
      weekly: "Weekly",
      biWeekly: "Bi-weekly",
      monthly: "Monthly",
      annual: "Annual",
      hoursPerDay: "Hours per day",
      hoursPerWeek: "Hours per week",
      totalHours: "Total hours",
      calculatedHours: "Calculated hours",
      manualHoursOverride: "Manual override",
      useCalculatedHours: "Use calculated hours",
      grossPayEstimate: "Gross pay estimate",
      payPeriodStart: "Pay period start",
      payPeriodEnd: "Pay period end",
      employeeSelectionLabel: "Included in this run",
    },
    employeeFilters: ["All departments", "Operations", "Salary", "Hourly"],
    employees: [
      {
        id: "maya",
        name: "Maya Chen",
        detail: "Operations · Salary · Ready",
        rateType: "monthly",
        rateAmount: 6250,
        hoursPerDay: 8,
        hoursPerWeek: 40,
        defaultSelected: true,
      },
      {
        id: "jonas",
        name: "Jonas Patel",
        detail: "Operations · Hourly · Time entry review",
        rateType: "hourly",
        rateAmount: 48,
        hoursPerDay: 8,
        hoursPerWeek: 40,
        defaultSelected: true,
      },
      {
        id: "amelia",
        name: "Amelia Brooks",
        detail: "Client success · Salary · Ready",
        rateType: "biWeekly",
        rateAmount: 2960,
        hoursPerDay: 8,
        hoursPerWeek: 40,
        defaultSelected: true,
      },
      {
        id: "noah",
        name: "Noah Singh",
        detail: "Field team · Hourly · Time entry review",
        rateType: "daily",
        rateAmount: 345,
        hoursPerDay: 8,
        hoursPerWeek: 40,
        defaultSelected: true,
      },
    ],
    reviewTotals: [
      { label: "Gross pay", id: "grossPay" },
      { label: "Estimated deductions", id: "deductions" },
      { label: "Estimated net pay", id: "netPay" },
    ],
    validation: {
      title: "We couldn't continue",
      selectEmployee: "Select at least one employee before reviewing payroll.",
      confirmationRequired: "Confirm that the payroll details are ready to submit.",
      noticeTitle: "Review note",
      noticeDescription: "Hours are estimated from the selected pay period and schedule. Review before submitting.",
    },
    confirmation: {
      title: "Submission audit",
      checkbox: "I have reviewed the payroll details and confirm this run is ready to submit.",
      auditNote:
        "Submitting payroll records the selected employees, totals, pay date, and user action in the audit trail.",
    },
    microcopy: {
      payPeriod: "Choose the earning period covered by this run.",
      payDate: "Employees will see this as the scheduled payment date.",
      payrollType: "Use off-cycle only when this run sits outside the regular schedule.",
      allEmployees: "Includes every active employee currently eligible for payroll.",
      rateType: "Choose how this employee is paid for the selected period.",
      rateAmount: "Enter the hourly, daily, weekly, bi-weekly, or monthly amount.",
      hoursPerDay: "Used for weekday-based hour estimates.",
      hoursPerWeek: "Used when the selected rate is weekly or bi-weekly.",
      totalHours: "Edit this only when the calculated schedule needs a manual adjustment.",
    },
    employeeDetail: {
      ready: "Ready",
      review: "Review",
    },
  },
  documents: {
    eyebrow: "Documents",
    title: "Documents",
    description: "Browse generated payroll records, employee letters, tax forms, and company files from one quiet workspace.",
    actions: {
      requestDocuments: "Request documents",
      uploadDocuments: "Upload documents",
    },
    actionLinks: {
      requestDocuments: "/documents",
      uploadDocuments: "/documents",
    },
    rowActions: {
      open: "Open",
      download: "Download",
    },
    columns: {
      type: "Type",
      date: "Date",
    },
    meta: {
      notEmployeeDocument: "Company file",
    },
    types: {
      payStub: "Pay stub",
      payrollRun: "Payroll run",
      letter: "Letter",
      taxForm: "Tax form",
    },
    entities: {
      companies: {
        northline: "Northline",
        willow: "Willow",
        harbor: "Harbor",
      },
      teams: {
        operations: "Operations",
        clientSuccess: "Client success",
        finance: "Finance",
        leadership: "Leadership",
      },
      employees: {
        mayaChen: "Maya Chen",
        jonasPatel: "Jonas Patel",
        ameliaBrooks: "Amelia Brooks",
        noahSingh: "Noah Singh",
      },
    },
    documentCount: {
      single: "document",
      plural: "documents",
    },
    emptyState: {
      title: "No documents match these filters",
      description: "Try a wider date range or clear one of the filters in the right rail.",
    },
    filters: {
      eyebrow: "Filters",
      title: "Refine documents",
      quickLabel: "Quick filters",
      companyLabel: "Company",
      teamLabel: "Team",
      employeeLabel: "Employee",
      dateRangeLabel: "Date range",
      quickFilters: [
        { id: "all", label: "All documents" },
        { id: "payroll", label: "Payroll docs" },
        { id: "employee", label: "Employee docs" },
        { id: "tax", label: "Tax forms" },
        { id: "company", label: "Company files" },
      ],
      companies: [
        { id: "all", label: "All companies" },
        { id: "northline", label: "Northline" },
        { id: "willow", label: "Willow" },
        { id: "harbor", label: "Harbor" },
      ],
      teams: [
        { id: "all", label: "All teams" },
        { id: "operations", label: "Operations" },
        { id: "client-success", label: "Client success" },
        { id: "finance", label: "Finance" },
        { id: "leadership", label: "Leadership" },
      ],
      employees: [
        { id: "all", label: "All employees" },
        { id: "maya-chen", label: "Maya Chen" },
        { id: "jonas-patel", label: "Jonas Patel" },
        { id: "amelia-brooks", label: "Amelia Brooks" },
        { id: "noah-singh", label: "Noah Singh" },
      ],
      dateRanges: [
        { id: "all", label: "All time" },
        { id: "april-2026", label: "April 2026" },
        { id: "q1-2026", label: "Q1 2026" },
        { id: "fy-2026", label: "2026" },
        { id: "fy-2025", label: "2025" },
      ],
    },
    items: {
      mayaPaystubApril: {
        title: "Maya Chen pay stub",
      },
      northlinePayrollRun: {
        title: "Northline payroll run packet",
      },
      jonasPaystubApril: {
        title: "Jonas Patel pay stub",
      },
      ameliaBonusLetter: {
        title: "Amelia Brooks bonus letter",
      },
      mayaVerificationLetter: {
        title: "Maya Chen employment verification",
      },
      mayaT4: {
        title: "Maya Chen T4",
      },
      jonasT4: {
        title: "Jonas Patel T4",
      },
      noahRoe: {
        title: "Noah Singh record of employment",
      },
      boardResolution: {
        title: "Board resolution package",
      },
    },
  },
  employee: {
    listTitle: "Employees",
    addEmployee: "Add employee",
    editEmployee: "Edit employee",
    noEmployeesTitle: "No employees yet",
    noEmployeesDescription: "Add employees to keep payroll, schedules, and compensation in one place.",
    searchPlaceholder: "Search employees",
    employmentDetails: "Employment details",
    compensation: "Compensation",
    workSchedule: "Work schedule",
    payrollSettings: "Payroll settings",
    personalDetails: "Personal details",
    taxAndIdentity: "Tax & identity",
    reviewAndSave: "Review & save",
    activity: "Activity",
    rateType: "Rate type",
    rateAmount: "Rate amount",
    name: "Name",
    fullName: "Full name",
    phone: "Phone",
    employeeAddress: "Employee address",
    streetAddress: "Street address",
    unit: "Unit / Apt",
    city: "City",
    province: "Province",
    postalCode: "Postal code",
    country: "Country",
    hoursPerDay: "Hours per day",
    hoursPerWeek: "Hours per week",
    employmentType: "Employment type",
    active: "Active",
    inactive: "Inactive",
    role: "Role",
    department: "Department / team",
    email: "Email",
    startDate: "Start date",
    workLocation: "Work location",
    paySchedule: "Pay schedule",
    eligibleForPayroll: "Eligible for payroll",
    defaultInPayroll: "Default inclusion in payroll",
    paymentMethod: "Payment method",
    taxProfile: "Tax profile",
    sin: "SIN",
    sinExpiryDate: "SIN expiry date",
    dateOfBirth: "Date of birth",
    taxProvince: "Tax province",
    secureFieldHint: "Visible only when you choose to reveal it.",
    revealSin: "Reveal",
    hideSin: "Hide",
    sinExpiryToggle: "SIN has an expiry date",
    paymentMethodPlaceholder: "Direct deposit coming soon",
    payrollHelperTitle: "Payroll calculation",
    reviewDescription: "Review each section before saving the employee profile.",
    summaryNotSet: "Not set",
    workingDays: "Working days",
    overrides: "Optional overrides",
    lastPaidDate: "Last paid",
    profileTitle: "Employee profile",
    createTitle: "Add employee",
    createDescription: "Move through a calm employee setup flow so payroll details stay clear and easy to review.",
    editDescription: "Update this employee profile one focused step at a time.",
    saveEmployee: "Save employee",
    deactivate: "Deactivate",
    nextStep: "Next",
    saveStep: "Save employee",
    stepLabel: "Step",
    ofLabel: "of",
    steps: {
      personal: "Personal details",
      employment: "Employment details",
      identity: "Tax & identity",
      compensation: "Compensation",
      payroll: "Payroll settings",
    },
    stepDescriptions: {
      personal: "Keep contact details and home address current for payroll records and employee documents.",
      employment: "Set the working arrangement and team details that shape how this employee appears across Credo.",
      identity: "Store sensitive tax details in a quieter, more secure-looking step.",
      compensation: "Define how payroll should calculate this employee's pay and expected hours.",
      payroll: "Confirm payroll defaults, payment method notes, and do one final review before saving.",
    },
    compensationHelper: {
      hourly: "Hourly pay uses the entered rate and multiplies it by hours in the pay period.",
      daily: "Daily pay uses the daily rate for each business day included in the pay period.",
      weekly: "Weekly pay prorates the weekly rate across the selected pay period.",
      biWeekly: "Bi-weekly pay prorates the bi-weekly rate across the selected pay period.",
      monthly: "Monthly pay prorates the monthly salary based on the business days in the selected pay period.",
      annual: "Annual pay estimates payroll by prorating salary across the business days in the year.",
    },
    fullTime: "Full-time",
    partTime: "Part-time",
    contractor: "Contractor",
    hourly: "Hourly",
    daily: "Daily",
    weekly: "Weekly",
    biWeekly: "Bi-weekly",
    monthly: "Monthly",
    annual: "Annual",
    filters: {
      all: "All",
      active: "Active",
      inactive: "Inactive",
    },
    quickSummary: {
      title: "Quick summary",
      eyebrow: "Employee",
      payrollReady: "Payroll ready",
      payrollExcluded: "Excluded from payroll",
    },
    activityLinks: {
      documents: "View pay stubs and letters",
      payrollHistory: "Payroll history coming soon",
    },
    validation: {
      title: "We couldn’t save this employee",
      nameRequired: "Add the employee name and try again.",
      emailRequired: "Add the employee email and try again.",
      addressRequired: "Complete the employee address and try again.",
      employmentRequired: "Add the role, start date, and employment details before continuing.",
      identityRequired: "Add the SIN, date of birth, and tax province before continuing.",
      sinExpiryRequired: "Add the SIN expiry date or turn that option off before continuing.",
      rateTypeRequired: "Select a rate type and try again.",
      rateAmountRequired: "Add the rate amount and try again.",
      payScheduleRequired: "Select a pay schedule and try again.",
    },
  },
  actions: {
    createCompany: {
      cannotCreateTitle: "We couldn’t create the company",
      legalNameMissing: "Add the legal name and try again.",
      genericDescription: "Check the required details and try again.",
    },
    profile: {
      companyNameRequired: "Company name is required. Add it and try again.",
      legalNameRequired: "Legal name is required. Add it and try again.",
      saveError: "We couldn’t save company details. Check required fields and try again.",
      updateError: "We couldn’t update company details. Check required fields and try again.",
      confirmError: "We couldn’t confirm the company yet. Review details and try again.",
    },
  },
} as const;

export type ContentDictionary = typeof en;
